runtime: python311

env_variables:
  GOOGLE_CLOUD_PROJECT: "youth-wellness-mcp"
  ENVIRONMENT: "production"

# Increase startup timeout
readiness_check:
  app_start_timeout_sec: 1800
  check_interval_sec: 10
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 2

liveness_check:
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Specify entry point
entrypoint: python main.py

instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 5
